# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crossbillUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1015, 748)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.imaging_mode_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.imaging_mode_groupBox.setEnabled(False)
        self.imaging_mode_groupBox.setMinimumSize(QtCore.QSize(0, 300))
        self.imaging_mode_groupBox.setMaximumSize(QtCore.QSize(700, 500))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.imaging_mode_groupBox.setFont(font)
        self.imaging_mode_groupBox.setObjectName("imaging_mode_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.imaging_mode_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 5, 0, 1, 4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem2, 7, 0, 1, 4)
        self.timedealy_label = QtWidgets.QLabel(self.imaging_mode_groupBox)
        self.timedealy_label.setMinimumSize(QtCore.QSize(300, 0))
        self.timedealy_label.setObjectName("timedealy_label")
        self.gridLayout_3.addWidget(self.timedealy_label, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 1, 1, 1)
        self.structural_groupBox = QtWidgets.QGroupBox(self.imaging_mode_groupBox)
        self.structural_groupBox.setEnabled(False)
        self.structural_groupBox.setMinimumSize(QtCore.QSize(0, 55))
        self.structural_groupBox.setObjectName("structural_groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.structural_groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.mode_struct_Yrange_lineEdit = QtWidgets.QLineEdit(self.structural_groupBox)
        self.mode_struct_Yrange_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.mode_struct_Yrange_lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.mode_struct_Yrange_lineEdit.setObjectName("mode_struct_Yrange_lineEdit")
        self.gridLayout_9.addWidget(self.mode_struct_Yrange_lineEdit, 0, 2, 1, 1)
        self.mode_struc_x_label = QtWidgets.QLabel(self.structural_groupBox)
        self.mode_struc_x_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mode_struc_x_label.setObjectName("mode_struc_x_label")
        self.gridLayout_9.addWidget(self.mode_struc_x_label, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.structural_groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 0, 7, 1, 1)
        self.mode_struct_Xrange_lineEdit = QtWidgets.QLineEdit(self.structural_groupBox)
        self.mode_struct_Xrange_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.mode_struct_Xrange_lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.mode_struct_Xrange_lineEdit.setObjectName("mode_struct_Xrange_lineEdit")
        self.gridLayout_9.addWidget(self.mode_struct_Xrange_lineEdit, 0, 6, 1, 1)
        self.mode_struc_StartStop_pushButton = QtWidgets.QPushButton(self.structural_groupBox)
        self.mode_struc_StartStop_pushButton.setMinimumSize(QtCore.QSize(130, 0))
        self.mode_struc_StartStop_pushButton.setMaximumSize(QtCore.QSize(130, 16777215))
        self.mode_struc_StartStop_pushButton.setObjectName("mode_struc_StartStop_pushButton")
        self.gridLayout_9.addWidget(self.mode_struc_StartStop_pushButton, 0, 10, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.structural_groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem4, 0, 4, 1, 1)
        self.mode_struc_label = QtWidgets.QLabel(self.structural_groupBox)
        self.mode_struc_label.setObjectName("mode_struc_label")
        self.gridLayout_9.addWidget(self.mode_struc_label, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem5, 0, 8, 1, 1)
        self.mode_struc_y_label = QtWidgets.QLabel(self.structural_groupBox)
        self.mode_struc_y_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mode_struc_y_label.setObjectName("mode_struc_y_label")
        self.gridLayout_9.addWidget(self.mode_struc_y_label, 0, 1, 1, 1)
        self.structuralcamframes_label = QtWidgets.QLabel(self.structural_groupBox)
        self.structuralcamframes_label.setMinimumSize(QtCore.QSize(70, 0))
        self.structuralcamframes_label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.structuralcamframes_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.structuralcamframes_label.setObjectName("structuralcamframes_label")
        self.gridLayout_9.addWidget(self.structuralcamframes_label, 0, 9, 1, 1)
        self.gridLayout_3.addWidget(self.structural_groupBox, 6, 0, 1, 4)
        self.timedelay_radioButton = QtWidgets.QRadioButton(self.imaging_mode_groupBox)
        self.timedelay_radioButton.setObjectName("timedelay_radioButton")
        self.gridLayout_3.addWidget(self.timedelay_radioButton, 0, 3, 1, 1)
        self.timedelay_lineEdit = QtWidgets.QLineEdit(self.imaging_mode_groupBox)
        self.timedelay_lineEdit.setObjectName("timedelay_lineEdit")
        self.gridLayout_3.addWidget(self.timedelay_lineEdit, 1, 2, 1, 2)
        self.imaging_mode_comboBox = QtWidgets.QComboBox(self.imaging_mode_groupBox)
        self.imaging_mode_comboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.imaging_mode_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.imaging_mode_comboBox.setObjectName("imaging_mode_comboBox")
        self.imaging_mode_comboBox.addItem("")
        self.imaging_mode_comboBox.addItem("")
        self.imaging_mode_comboBox.addItem("")
        self.gridLayout_3.addWidget(self.imaging_mode_comboBox, 0, 0, 1, 1)
        self.functional_groupBox = QtWidgets.QGroupBox(self.imaging_mode_groupBox)
        self.functional_groupBox.setEnabled(False)
        self.functional_groupBox.setMinimumSize(QtCore.QSize(0, 55))
        self.functional_groupBox.setObjectName("functional_groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.functional_groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.mode_fun_StartStop_pushButton = QtWidgets.QPushButton(self.functional_groupBox)
        self.mode_fun_StartStop_pushButton.setMinimumSize(QtCore.QSize(130, 0))
        self.mode_fun_StartStop_pushButton.setMaximumSize(QtCore.QSize(130, 16777215))
        self.mode_fun_StartStop_pushButton.setObjectName("mode_fun_StartStop_pushButton")
        self.gridLayout_6.addWidget(self.mode_fun_StartStop_pushButton, 1, 5, 1, 1)
        self.mode_fun_scantime_label = QtWidgets.QLabel(self.functional_groupBox)
        self.mode_fun_scantime_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mode_fun_scantime_label.setObjectName("mode_fun_scantime_label")
        self.gridLayout_6.addWidget(self.mode_fun_scantime_label, 1, 2, 1, 1)
        self.mode_fun_scantime_lineEdit = QtWidgets.QLineEdit(self.functional_groupBox)
        self.mode_fun_scantime_lineEdit.setMinimumSize(QtCore.QSize(75, 0))
        self.mode_fun_scantime_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.mode_fun_scantime_lineEdit.setObjectName("mode_fun_scantime_lineEdit")
        self.gridLayout_6.addWidget(self.mode_fun_scantime_lineEdit, 1, 3, 1, 1)
        self.mode_fun_label = QtWidgets.QLabel(self.functional_groupBox)
        self.mode_fun_label.setObjectName("mode_fun_label")
        self.gridLayout_6.addWidget(self.mode_fun_label, 1, 0, 1, 1)
        self.functionalcamframes_label = QtWidgets.QLabel(self.functional_groupBox)
        self.functionalcamframes_label.setMinimumSize(QtCore.QSize(60, 0))
        self.functionalcamframes_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.functionalcamframes_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.functionalcamframes_label.setObjectName("functionalcamframes_label")
        self.gridLayout_6.addWidget(self.functionalcamframes_label, 1, 4, 1, 1)
        self.gridLayout_3.addWidget(self.functional_groupBox, 4, 0, 1, 4)
        self.gridLayout.addWidget(self.imaging_mode_groupBox, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 380))
        self.tabWidget.setObjectName("tabWidget")
        self.cfg_tab = QtWidgets.QWidget()
        self.cfg_tab.setObjectName("cfg_tab")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.cfg_tab)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.cfgdone_pushButton = QtWidgets.QPushButton(self.cfg_tab)
        self.cfgdone_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cfgdone_pushButton.setFont(font)
        self.cfgdone_pushButton.setObjectName("cfgdone_pushButton")
        self.gridLayout_12.addWidget(self.cfgdone_pushButton, 3, 3, 1, 1)
        self.cfgsave_pushButton = QtWidgets.QPushButton(self.cfg_tab)
        self.cfgsave_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cfgsave_pushButton.setFont(font)
        self.cfgsave_pushButton.setObjectName("cfgsave_pushButton")
        self.gridLayout_12.addWidget(self.cfgsave_pushButton, 3, 2, 1, 1)
        self.cfgload_pushButton = QtWidgets.QPushButton(self.cfg_tab)
        self.cfgload_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cfgload_pushButton.setFont(font)
        self.cfgload_pushButton.setObjectName("cfgload_pushButton")
        self.gridLayout_12.addWidget(self.cfgload_pushButton, 3, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem6, 3, 0, 1, 1)
        self.optics_groupBox = QtWidgets.QGroupBox(self.cfg_tab)
        self.optics_groupBox.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.optics_groupBox.setFont(font)
        self.optics_groupBox.setObjectName("optics_groupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.optics_groupBox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.MO1make_comboBox = QtWidgets.QComboBox(self.optics_groupBox)
        self.MO1make_comboBox.setObjectName("MO1make_comboBox")
        self.MO1make_comboBox.addItem("")
        self.MO1make_comboBox.addItem("")
        self.MO1make_comboBox.addItem("")
        self.MO1make_comboBox.addItem("")
        self.MO1make_comboBox.addItem("")
        self.gridLayout_10.addWidget(self.MO1make_comboBox, 1, 1, 1, 1)
        self.MO1mag_comboBox = QtWidgets.QComboBox(self.optics_groupBox)
        self.MO1mag_comboBox.setMinimumSize(QtCore.QSize(75, 0))
        self.MO1mag_comboBox.setObjectName("MO1mag_comboBox")
        self.MO1mag_comboBox.addItem("")
        self.MO1mag_comboBox.addItem("")
        self.MO1mag_comboBox.addItem("")
        self.MO1mag_comboBox.addItem("")
        self.MO1mag_comboBox.addItem("")
        self.MO1mag_comboBox.addItem("")
        self.MO1mag_comboBox.addItem("")
        self.MO1mag_comboBox.addItem("")
        self.MO1mag_comboBox.addItem("")
        self.MO1mag_comboBox.addItem("")
        self.MO1mag_comboBox.addItem("")
        self.gridLayout_10.addWidget(self.MO1mag_comboBox, 1, 2, 1, 1)
        self.TL1_lineEdit = QtWidgets.QLineEdit(self.optics_groupBox)
        self.TL1_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.TL1_lineEdit.setObjectName("TL1_lineEdit")
        self.gridLayout_10.addWidget(self.TL1_lineEdit, 1, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.optics_groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 2, 0, 1, 1)
        self.MO2make_comboBox = QtWidgets.QComboBox(self.optics_groupBox)
        self.MO2make_comboBox.setObjectName("MO2make_comboBox")
        self.MO2make_comboBox.addItem("")
        self.MO2make_comboBox.addItem("")
        self.MO2make_comboBox.addItem("")
        self.MO2make_comboBox.addItem("")
        self.MO2make_comboBox.addItem("")
        self.gridLayout_10.addWidget(self.MO2make_comboBox, 2, 1, 1, 1)
        self.MO2mag_comboBox = QtWidgets.QComboBox(self.optics_groupBox)
        self.MO2mag_comboBox.setMinimumSize(QtCore.QSize(75, 0))
        self.MO2mag_comboBox.setObjectName("MO2mag_comboBox")
        self.MO2mag_comboBox.addItem("")
        self.MO2mag_comboBox.addItem("")
        self.MO2mag_comboBox.addItem("")
        self.MO2mag_comboBox.addItem("")
        self.MO2mag_comboBox.addItem("")
        self.MO2mag_comboBox.addItem("")
        self.MO2mag_comboBox.addItem("")
        self.MO2mag_comboBox.addItem("")
        self.MO2mag_comboBox.addItem("")
        self.MO2mag_comboBox.addItem("")
        self.MO2mag_comboBox.addItem("")
        self.gridLayout_10.addWidget(self.MO2mag_comboBox, 2, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.optics_groupBox)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 2, 4, 1, 1)
        self.TL2_lineEdit = QtWidgets.QLineEdit(self.optics_groupBox)
        self.TL2_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.TL2_lineEdit.setObjectName("TL2_lineEdit")
        self.gridLayout_10.addWidget(self.TL2_lineEdit, 2, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.optics_groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 2, 7, 1, 1)
        self.SL2_lineEdit = QtWidgets.QLineEdit(self.optics_groupBox)
        self.SL2_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SL2_lineEdit.setObjectName("SL2_lineEdit")
        self.gridLayout_10.addWidget(self.SL2_lineEdit, 2, 8, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.optics_groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 3, 0, 1, 1)
        self.MO3make_comboBox = QtWidgets.QComboBox(self.optics_groupBox)
        self.MO3make_comboBox.setObjectName("MO3make_comboBox")
        self.MO3make_comboBox.addItem("")
        self.MO3make_comboBox.addItem("")
        self.MO3make_comboBox.addItem("")
        self.MO3make_comboBox.addItem("")
        self.MO3make_comboBox.addItem("")
        self.gridLayout_10.addWidget(self.MO3make_comboBox, 3, 1, 1, 1)
        self.MO3mag_comboBox = QtWidgets.QComboBox(self.optics_groupBox)
        self.MO3mag_comboBox.setMinimumSize(QtCore.QSize(75, 0))
        self.MO3mag_comboBox.setObjectName("MO3mag_comboBox")
        self.MO3mag_comboBox.addItem("")
        self.MO3mag_comboBox.addItem("")
        self.MO3mag_comboBox.addItem("")
        self.MO3mag_comboBox.addItem("")
        self.MO3mag_comboBox.addItem("")
        self.MO3mag_comboBox.addItem("")
        self.MO3mag_comboBox.addItem("")
        self.MO3mag_comboBox.addItem("")
        self.MO3mag_comboBox.addItem("")
        self.MO3mag_comboBox.addItem("")
        self.MO3mag_comboBox.addItem("")
        self.gridLayout_10.addWidget(self.MO3mag_comboBox, 3, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.optics_groupBox)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 3, 4, 1, 1)
        self.TL3_lineEdit = QtWidgets.QLineEdit(self.optics_groupBox)
        self.TL3_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.TL3_lineEdit.setObjectName("TL3_lineEdit")
        self.gridLayout_10.addWidget(self.TL3_lineEdit, 3, 5, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.optics_groupBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_10.addWidget(self.label_17, 3, 7, 1, 1)
        self.SL3_lineEdit = QtWidgets.QLineEdit(self.optics_groupBox)
        self.SL3_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SL3_lineEdit.setObjectName("SL3_lineEdit")
        self.gridLayout_10.addWidget(self.SL3_lineEdit, 3, 8, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.optics_groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 1, 7, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.optics_groupBox)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 1, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.optics_groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 1, 0, 1, 1)
        self.SL1_lineEdit = QtWidgets.QLineEdit(self.optics_groupBox)
        self.SL1_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SL1_lineEdit.setObjectName("SL1_lineEdit")
        self.gridLayout_10.addWidget(self.SL1_lineEdit, 1, 8, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem7, 1, 6, 3, 1)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem8, 1, 3, 3, 1)
        self.gridLayout_12.addWidget(self.optics_groupBox, 2, 0, 1, 4)
        self.G2_groupBox = QtWidgets.QGroupBox(self.cfg_tab)
        self.G2_groupBox.setMaximumSize(QtCore.QSize(250, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.G2_groupBox.setFont(font)
        self.G2_groupBox.setObjectName("G2_groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.G2_groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_4 = QtWidgets.QLabel(self.G2_groupBox)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 0, 0, 1, 1)
        self.G2vpd_lineEdit = QtWidgets.QLineEdit(self.G2_groupBox)
        self.G2vpd_lineEdit.setEnabled(True)
        self.G2vpd_lineEdit.setMaximumSize(QtCore.QSize(65, 16777215))
        self.G2vpd_lineEdit.setObjectName("G2vpd_lineEdit")
        self.gridLayout_8.addWidget(self.G2vpd_lineEdit, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.G2_groupBox, 1, 0, 1, 2)
        self.G1_groupBox = QtWidgets.QGroupBox(self.cfg_tab)
        self.G1_groupBox.setMaximumSize(QtCore.QSize(250, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.G1_groupBox.setFont(font)
        self.G1_groupBox.setObjectName("G1_groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.G1_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.G1vpd_lineEdit = QtWidgets.QLineEdit(self.G1_groupBox)
        self.G1vpd_lineEdit.setEnabled(True)
        self.G1vpd_lineEdit.setMaximumSize(QtCore.QSize(65, 16777215))
        self.G1vpd_lineEdit.setObjectName("G1vpd_lineEdit")
        self.gridLayout_2.addWidget(self.G1vpd_lineEdit, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.G1_groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 2)
        self.gridLayout_12.addWidget(self.G1_groupBox, 0, 0, 1, 2)
        self.camera_groupBox = QtWidgets.QGroupBox(self.cfg_tab)
        self.camera_groupBox.setMaximumSize(QtCore.QSize(300, 180))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.camera_groupBox.setFont(font)
        self.camera_groupBox.setObjectName("camera_groupBox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.camera_groupBox)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_19 = QtWidgets.QLabel(self.camera_groupBox)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 1, 0, 1, 1)
        self.pxsize_lineEdit = QtWidgets.QLineEdit(self.camera_groupBox)
        self.pxsize_lineEdit.setObjectName("pxsize_lineEdit")
        self.gridLayout_11.addWidget(self.pxsize_lineEdit, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.camera_groupBox)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.camera_groupBox)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 0, 0, 1, 1)
        self.heightpx_lineEdit = QtWidgets.QLineEdit(self.camera_groupBox)
        self.heightpx_lineEdit.setObjectName("heightpx_lineEdit")
        self.gridLayout_11.addWidget(self.heightpx_lineEdit, 2, 1, 1, 1)
        self.widthpx_lineEdit = QtWidgets.QLineEdit(self.camera_groupBox)
        self.widthpx_lineEdit.setObjectName("widthpx_lineEdit")
        self.gridLayout_11.addWidget(self.widthpx_lineEdit, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.camera_groupBox)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 3, 0, 1, 2)
        self.gridLayout_12.addWidget(self.camera_groupBox, 0, 2, 2, 2)
        self.tabWidget.addTab(self.cfg_tab, "")
        self.control_tab = QtWidgets.QWidget()
        self.control_tab.setObjectName("control_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.control_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.daq_groupBox = QtWidgets.QGroupBox(self.control_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.daq_groupBox.sizePolicy().hasHeightForWidth())
        self.daq_groupBox.setSizePolicy(sizePolicy)
        self.daq_groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.daq_groupBox.setMaximumSize(QtCore.QSize(700, 180))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.daq_groupBox.setFont(font)
        self.daq_groupBox.setObjectName("daq_groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.daq_groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.G1freq_label = QtWidgets.QLabel(self.daq_groupBox)
        self.G1freq_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.G1freq_label.setObjectName("G1freq_label")
        self.gridLayout_5.addWidget(self.G1freq_label, 6, 5, 1, 1)
        self.scanrange1_lineEdit = QtWidgets.QLineEdit(self.daq_groupBox)
        self.scanrange1_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scanrange1_lineEdit.setObjectName("scanrange1_lineEdit")
        self.gridLayout_5.addWidget(self.scanrange1_lineEdit, 1, 6, 1, 1)
        self.offset2_label = QtWidgets.QLabel(self.daq_groupBox)
        self.offset2_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.offset2_label.setObjectName("offset2_label")
        self.gridLayout_5.addWidget(self.offset2_label, 4, 11, 1, 1)
        self.daq_trigenable_radioButton = QtWidgets.QRadioButton(self.daq_groupBox)
        self.daq_trigenable_radioButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.daq_trigenable_radioButton.setObjectName("daq_trigenable_radioButton")
        self.gridLayout_5.addWidget(self.daq_trigenable_radioButton, 6, 13, 1, 1)
        self.connect_daq_pushButton = QtWidgets.QPushButton(self.daq_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_daq_pushButton.sizePolicy().hasHeightForWidth())
        self.connect_daq_pushButton.setSizePolicy(sizePolicy)
        self.connect_daq_pushButton.setMinimumSize(QtCore.QSize(90, 0))
        self.connect_daq_pushButton.setObjectName("connect_daq_pushButton")
        self.gridLayout_5.addWidget(self.connect_daq_pushButton, 0, 1, 1, 1)
        self.G2_label = QtWidgets.QLabel(self.daq_groupBox)
        self.G2_label.setObjectName("G2_label")
        self.gridLayout_5.addWidget(self.G2_label, 4, 1, 1, 1)
        self.camtrig_label = QtWidgets.QLabel(self.daq_groupBox)
        self.camtrig_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.camtrig_label.setObjectName("camtrig_label")
        self.gridLayout_5.addWidget(self.camtrig_label, 6, 11, 1, 1)
        self.daqstatus_LED = QtWidgets.QLabel(self.daq_groupBox)
        self.daqstatus_LED.setMaximumSize(QtCore.QSize(20, 20))
        self.daqstatus_LED.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.daqstatus_LED.setText("")
        self.daqstatus_LED.setPixmap(QtGui.QPixmap(":/icons/icons/Gray_btn.png"))
        self.daqstatus_LED.setScaledContents(True)
        self.daqstatus_LED.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.daqstatus_LED.setObjectName("daqstatus_LED")
        self.gridLayout_5.addWidget(self.daqstatus_LED, 0, 0, 1, 1)
        self.scanrange_label = QtWidgets.QLabel(self.daq_groupBox)
        self.scanrange_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scanrange_label.setObjectName("scanrange_label")
        self.gridLayout_5.addWidget(self.scanrange_label, 1, 2, 1, 4)
        self.scanrange2_label = QtWidgets.QLabel(self.daq_groupBox)
        self.scanrange2_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scanrange2_label.setObjectName("scanrange2_label")
        self.gridLayout_5.addWidget(self.scanrange2_label, 4, 2, 1, 4)
        self.offset2_lineEdit = QtWidgets.QLineEdit(self.daq_groupBox)
        self.offset2_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.offset2_lineEdit.setObjectName("offset2_lineEdit")
        self.gridLayout_5.addWidget(self.offset2_lineEdit, 4, 12, 1, 2)
        self.VPS_comboBox = QtWidgets.QComboBox(self.daq_groupBox)
        self.VPS_comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.VPS_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.VPS_comboBox.setEditable(True)
        self.VPS_comboBox.setObjectName("VPS_comboBox")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.VPS_comboBox.addItem("")
        self.gridLayout_5.addWidget(self.VPS_comboBox, 6, 6, 1, 1)
        self.TTLfreq_comboBox = QtWidgets.QComboBox(self.daq_groupBox)
        self.TTLfreq_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TTLfreq_comboBox.setEditable(True)
        self.TTLfreq_comboBox.setObjectName("TTLfreq_comboBox")
        self.TTLfreq_comboBox.addItem("")
        self.TTLfreq_comboBox.addItem("")
        self.TTLfreq_comboBox.addItem("")
        self.TTLfreq_comboBox.addItem("")
        self.TTLfreq_comboBox.addItem("")
        self.TTLfreq_comboBox.addItem("")
        self.TTLfreq_comboBox.addItem("")
        self.TTLfreq_comboBox.addItem("")
        self.TTLfreq_comboBox.addItem("")
        self.TTLfreq_comboBox.addItem("")
        self.gridLayout_5.addWidget(self.TTLfreq_comboBox, 6, 12, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 6, 10, 1, 1)
        self.offset_label = QtWidgets.QLabel(self.daq_groupBox)
        self.offset_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.offset_label.setObjectName("offset_label")
        self.gridLayout_5.addWidget(self.offset_label, 1, 11, 1, 1)
        self.offset1_lineEdit = QtWidgets.QLineEdit(self.daq_groupBox)
        self.offset1_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.offset1_lineEdit.setObjectName("offset1_lineEdit")
        self.gridLayout_5.addWidget(self.offset1_lineEdit, 1, 12, 1, 2)
        self.scanrange2_lineEdit = QtWidgets.QLineEdit(self.daq_groupBox)
        self.scanrange2_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scanrange2_lineEdit.setObjectName("scanrange2_lineEdit")
        self.gridLayout_5.addWidget(self.scanrange2_lineEdit, 4, 6, 1, 1)
        self.DAQthreadCount_lineEdit = QtWidgets.QLineEdit(self.daq_groupBox)
        self.DAQthreadCount_lineEdit.setEnabled(False)
        self.DAQthreadCount_lineEdit.setStyleSheet("")
        self.DAQthreadCount_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DAQthreadCount_lineEdit.setObjectName("DAQthreadCount_lineEdit")
        self.gridLayout_5.addWidget(self.DAQthreadCount_lineEdit, 0, 12, 1, 2)
        self.laser_comboBox = QtWidgets.QComboBox(self.daq_groupBox)
        self.laser_comboBox.setMinimumSize(QtCore.QSize(90, 0))
        self.laser_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.laser_comboBox.setObjectName("laser_comboBox")
        self.laser_comboBox.addItem("")
        self.laser_comboBox.addItem("")
        self.laser_comboBox.addItem("")
        self.gridLayout_5.addWidget(self.laser_comboBox, 6, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem10, 6, 2, 1, 3)
        self.G1_label = QtWidgets.QLabel(self.daq_groupBox)
        self.G1_label.setObjectName("G1_label")
        self.gridLayout_5.addWidget(self.G1_label, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.daq_groupBox)
        self.stage_groupBox = QtWidgets.QGroupBox(self.control_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage_groupBox.sizePolicy().hasHeightForWidth())
        self.stage_groupBox.setSizePolicy(sizePolicy)
        self.stage_groupBox.setMaximumSize(QtCore.QSize(700, 180))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.stage_groupBox.setFont(font)
        self.stage_groupBox.setObjectName("stage_groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.stage_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem11 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 4, 2, 1, 1)
        self.stagestatus_LED = QtWidgets.QLabel(self.stage_groupBox)
        self.stagestatus_LED.setMaximumSize(QtCore.QSize(20, 20))
        self.stagestatus_LED.setText("")
        self.stagestatus_LED.setPixmap(QtGui.QPixmap(":/icons/icons/Gray_btn.png"))
        self.stagestatus_LED.setScaledContents(True)
        self.stagestatus_LED.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.stagestatus_LED.setObjectName("stagestatus_LED")
        self.gridLayout_4.addWidget(self.stagestatus_LED, 0, 0, 1, 1)
        self.speed_label = QtWidgets.QLabel(self.stage_groupBox)
        self.speed_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.speed_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.speed_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speed_label.setObjectName("speed_label")
        self.gridLayout_4.addWidget(self.speed_label, 2, 11, 1, 4)
        self.recenter_pushButton = QtWidgets.QPushButton(self.stage_groupBox)
        self.recenter_pushButton.setMinimumSize(QtCore.QSize(90, 0))
        self.recenter_pushButton.setObjectName("recenter_pushButton")
        self.gridLayout_4.addWidget(self.recenter_pushButton, 2, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 4, 10, 1, 1)
        self.haltstage_Button = QtWidgets.QPushButton(self.stage_groupBox)
        self.haltstage_Button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.haltstage_Button.setStyleSheet("")
        self.haltstage_Button.setObjectName("haltstage_Button")
        self.gridLayout_4.addWidget(self.haltstage_Button, 5, 15, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.stage_groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 7, 1, 3)
        spacerItem13 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 4, 6, 1, 1)
        self.stagemotion_LED = QtWidgets.QLabel(self.stage_groupBox)
        self.stagemotion_LED.setMaximumSize(QtCore.QSize(30, 30))
        self.stagemotion_LED.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stagemotion_LED.setText("")
        self.stagemotion_LED.setPixmap(QtGui.QPixmap(":/icons/icons/Gray_btn.png"))
        self.stagemotion_LED.setScaledContents(True)
        self.stagemotion_LED.setAlignment(QtCore.Qt.AlignCenter)
        self.stagemotion_LED.setObjectName("stagemotion_LED")
        self.gridLayout_4.addWidget(self.stagemotion_LED, 4, 8, 1, 1)
        self.velocity_comboBox = QtWidgets.QComboBox(self.stage_groupBox)
        self.velocity_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.velocity_comboBox.setObjectName("velocity_comboBox")
        self.velocity_comboBox.addItem("")
        self.velocity_comboBox.addItem("")
        self.velocity_comboBox.addItem("")
        self.velocity_comboBox.addItem("")
        self.velocity_comboBox.addItem("")
        self.velocity_comboBox.addItem("")
        self.velocity_comboBox.addItem("")
        self.velocity_comboBox.addItem("")
        self.velocity_comboBox.addItem("")
        self.velocity_comboBox.addItem("")
        self.gridLayout_4.addWidget(self.velocity_comboBox, 2, 15, 1, 1)
        self.connect_stage_pushButton = QtWidgets.QPushButton(self.stage_groupBox)
        self.connect_stage_pushButton.setMinimumSize(QtCore.QSize(90, 0))
        self.connect_stage_pushButton.setObjectName("connect_stage_pushButton")
        self.gridLayout_4.addWidget(self.connect_stage_pushButton, 0, 1, 1, 1)
        self.reset_stagelimit_pushButton = QtWidgets.QPushButton(self.stage_groupBox)
        self.reset_stagelimit_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.reset_stagelimit_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.reset_stagelimit_pushButton.setStyleSheet("QPushButton {\n"
"     background-color: rgba(0, 0, 0, 0);     \n"
" }\n"
" QPushButton:hover {\n"
"     background-color: rgba(200, 200, 200, 40);\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgba(200, 200, 200, 80);\n"
" }")
        self.reset_stagelimit_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset_stagelimit_pushButton.setIcon(icon1)
        self.reset_stagelimit_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.reset_stagelimit_pushButton.setObjectName("reset_stagelimit_pushButton")
        self.gridLayout_4.addWidget(self.reset_stagelimit_pushButton, 4, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.stage_groupBox)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 3, 1, 3)
        self.Xneg_pushButton = QtWidgets.QPushButton(self.stage_groupBox)
        self.Xneg_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.Xneg_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Xneg_pushButton.setFont(font)
        self.Xneg_pushButton.setStyleSheet("QPushButton:disabled{\n"
"background-color:rgb(150, 128, 128);}")
        self.Xneg_pushButton.setObjectName("Xneg_pushButton")
        self.gridLayout_4.addWidget(self.Xneg_pushButton, 4, 7, 1, 1)
        self.Yneg_pushButton = QtWidgets.QPushButton(self.stage_groupBox)
        self.Yneg_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.Yneg_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Yneg_pushButton.setFont(font)
        self.Yneg_pushButton.setStyleSheet("QPushButton:disabled{\n"
"background-color:rgb(150, 128, 128);}")
        self.Yneg_pushButton.setObjectName("Yneg_pushButton")
        self.gridLayout_4.addWidget(self.Yneg_pushButton, 5, 8, 1, 1)
        self.Ypos_pushButton = QtWidgets.QPushButton(self.stage_groupBox)
        self.Ypos_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.Ypos_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Ypos_pushButton.setFont(font)
        self.Ypos_pushButton.setStyleSheet("QPushButton:disabled{\n"
"background-color:rgb(150, 128, 128);}\n"
"")
        self.Ypos_pushButton.setObjectName("Ypos_pushButton")
        self.gridLayout_4.addWidget(self.Ypos_pushButton, 2, 8, 1, 1)
        self.Xpos_pushButton = QtWidgets.QPushButton(self.stage_groupBox)
        self.Xpos_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.Xpos_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Xpos_pushButton.setFont(font)
        self.Xpos_pushButton.setStyleSheet("QPushButton:disabled{\n"
"background-color:rgb(150, 128, 128);}")
        self.Xpos_pushButton.setObjectName("Xpos_pushButton")
        self.gridLayout_4.addWidget(self.Xpos_pushButton, 4, 9, 1, 1)
        self.Ypos_lim_pushButton = QtWidgets.QPushButton(self.stage_groupBox)
        self.Ypos_lim_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.Ypos_lim_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Ypos_lim_pushButton.setFont(font)
        self.Ypos_lim_pushButton.setStyleSheet("QPushButton:disabled{\n"
"background-color:rgb(150, 128, 128);}\n"
"\n"
"QPushButton:checked{\n"
"background-color:rgb(200, 128, 128);}")
        self.Ypos_lim_pushButton.setObjectName("Ypos_lim_pushButton")
        self.gridLayout_4.addWidget(self.Ypos_lim_pushButton, 2, 4, 1, 1)
        self.Xpos_lim_pushButton = QtWidgets.QPushButton(self.stage_groupBox)
        self.Xpos_lim_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.Xpos_lim_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Xpos_lim_pushButton.setFont(font)
        self.Xpos_lim_pushButton.setStyleSheet("QPushButton:disabled{\n"
"background-color:rgb(150, 128, 128);}\n"
"\n"
"QPushButton:checked{\n"
"background-color:rgb(200, 128, 128);}")
        self.Xpos_lim_pushButton.setObjectName("Xpos_lim_pushButton")
        self.gridLayout_4.addWidget(self.Xpos_lim_pushButton, 4, 5, 1, 1)
        self.Xneg_lim_pushButton = QtWidgets.QPushButton(self.stage_groupBox)
        self.Xneg_lim_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.Xneg_lim_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Xneg_lim_pushButton.setFont(font)
        self.Xneg_lim_pushButton.setStyleSheet("QPushButton:disabled{\n"
"background-color:rgb(150, 128, 128);}\n"
"\n"
"QPushButton:checked{\n"
"background-color:rgb(200, 128, 128);}")
        self.Xneg_lim_pushButton.setObjectName("Xneg_lim_pushButton")
        self.gridLayout_4.addWidget(self.Xneg_lim_pushButton, 4, 3, 1, 1)
        self.Yneg_lim_pushButton = QtWidgets.QPushButton(self.stage_groupBox)
        self.Yneg_lim_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.Yneg_lim_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Yneg_lim_pushButton.setFont(font)
        self.Yneg_lim_pushButton.setStyleSheet("QPushButton:disabled{\n"
"background-color:rgb(150, 128, 128);}\n"
"\n"
"QPushButton:checked{\n"
"background-color:rgb(200, 128, 128);}")
        self.Yneg_lim_pushButton.setObjectName("Yneg_lim_pushButton")
        self.gridLayout_4.addWidget(self.Yneg_lim_pushButton, 5, 4, 1, 1)
        self.StageThreadCount_lineEdit = QtWidgets.QLineEdit(self.stage_groupBox)
        self.StageThreadCount_lineEdit.setEnabled(False)
        self.StageThreadCount_lineEdit.setStyleSheet("color: rgb(36, 36, 36);")
        self.StageThreadCount_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.StageThreadCount_lineEdit.setObjectName("StageThreadCount_lineEdit")
        self.gridLayout_4.addWidget(self.StageThreadCount_lineEdit, 0, 15, 1, 1)
        self.location_display_label = QtWidgets.QLabel(self.stage_groupBox)
        self.location_display_label.setMinimumSize(QtCore.QSize(90, 0))
        self.location_display_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.location_display_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.location_display_label.setObjectName("location_display_label")
        self.gridLayout_4.addWidget(self.location_display_label, 5, 9, 1, 6)
        self.stepenable_radioButton = QtWidgets.QRadioButton(self.stage_groupBox)
        self.stepenable_radioButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.stepenable_radioButton.setObjectName("stepenable_radioButton")
        self.gridLayout_4.addWidget(self.stepenable_radioButton, 4, 14, 1, 1)
        self.movestep_lineEdit = QtWidgets.QLineEdit(self.stage_groupBox)
        self.movestep_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.movestep_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.movestep_lineEdit.setObjectName("movestep_lineEdit")
        self.gridLayout_4.addWidget(self.movestep_lineEdit, 4, 15, 1, 1)
        self.verticalLayout.addWidget(self.stage_groupBox)
        self.tabWidget.addTab(self.control_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Crossbill mini"))
        self.imaging_mode_groupBox.setTitle(_translate("MainWindow", "Imaging mode(s)"))
        self.timedealy_label.setText(_translate("MainWindow", "Time delay (seconds) - useful for time-lapse"))
        self.structural_groupBox.setTitle(_translate("MainWindow", "Structural (Galvo sweeps and stage moves)"))
        self.mode_struc_x_label.setText(_translate("MainWindow", "X "))
        self.label_6.setText(_translate("MainWindow", "µm"))
        self.mode_struc_StartStop_pushButton.setText(_translate("MainWindow", "Start"))
        self.label_5.setText(_translate("MainWindow", "µm"))
        self.mode_struc_label.setText(_translate("MainWindow", "Scan-range: ΔY: XYZ µm & Total:"))
        self.mode_struc_y_label.setText(_translate("MainWindow", "Y"))
        self.structuralcamframes_label.setText(_translate("MainWindow", "#frames"))
        self.timedelay_radioButton.setText(_translate("MainWindow", "Y/N"))
        self.timedelay_lineEdit.setText(_translate("MainWindow", "0"))
        self.imaging_mode_comboBox.setItemText(0, _translate("MainWindow", "(Select mode)"))
        self.imaging_mode_comboBox.setItemText(1, _translate("MainWindow", "Functional"))
        self.imaging_mode_comboBox.setItemText(2, _translate("MainWindow", "Structural"))
        self.functional_groupBox.setTitle(_translate("MainWindow", "Functional (Galvo sweeps but no stage motion)"))
        self.mode_fun_StartStop_pushButton.setText(_translate("MainWindow", "Start"))
        self.mode_fun_scantime_label.setText(_translate("MainWindow", "Scan-time (s)"))
        self.mode_fun_label.setText(_translate("MainWindow", "NN planes at NN VPS (NN sweeps)"))
        self.functionalcamframes_label.setText(_translate("MainWindow", "#frames"))
        self.cfgdone_pushButton.setText(_translate("MainWindow", "Done"))
        self.cfgsave_pushButton.setText(_translate("MainWindow", "Save"))
        self.cfgload_pushButton.setText(_translate("MainWindow", "Load"))
        self.optics_groupBox.setTitle(_translate("MainWindow", "Optics"))
        self.MO1make_comboBox.setItemText(0, _translate("MainWindow", "Leica"))
        self.MO1make_comboBox.setItemText(1, _translate("MainWindow", "Mitutoyo"))
        self.MO1make_comboBox.setItemText(2, _translate("MainWindow", "Nikon"))
        self.MO1make_comboBox.setItemText(3, _translate("MainWindow", "Olympus"))
        self.MO1make_comboBox.setItemText(4, _translate("MainWindow", "Zeiss"))
        self.MO1mag_comboBox.setItemText(0, _translate("MainWindow", "4x"))
        self.MO1mag_comboBox.setItemText(1, _translate("MainWindow", "5x"))
        self.MO1mag_comboBox.setItemText(2, _translate("MainWindow", "10x"))
        self.MO1mag_comboBox.setItemText(3, _translate("MainWindow", "16x"))
        self.MO1mag_comboBox.setItemText(4, _translate("MainWindow", "20x"))
        self.MO1mag_comboBox.setItemText(5, _translate("MainWindow", "25x"))
        self.MO1mag_comboBox.setItemText(6, _translate("MainWindow", "30x"))
        self.MO1mag_comboBox.setItemText(7, _translate("MainWindow", "40x"))
        self.MO1mag_comboBox.setItemText(8, _translate("MainWindow", "50x"))
        self.MO1mag_comboBox.setItemText(9, _translate("MainWindow", "60x"))
        self.MO1mag_comboBox.setItemText(10, _translate("MainWindow", "100x"))
        self.TL1_lineEdit.setPlaceholderText(_translate("MainWindow", "focal length"))
        self.label_9.setText(_translate("MainWindow", "MO2"))
        self.MO2make_comboBox.setItemText(0, _translate("MainWindow", "Leica"))
        self.MO2make_comboBox.setItemText(1, _translate("MainWindow", "Mitutoyo"))
        self.MO2make_comboBox.setItemText(2, _translate("MainWindow", "Nikon"))
        self.MO2make_comboBox.setItemText(3, _translate("MainWindow", "Olympus"))
        self.MO2make_comboBox.setItemText(4, _translate("MainWindow", "Zeiss"))
        self.MO2mag_comboBox.setItemText(0, _translate("MainWindow", "4x"))
        self.MO2mag_comboBox.setItemText(1, _translate("MainWindow", "5x"))
        self.MO2mag_comboBox.setItemText(2, _translate("MainWindow", "10x"))
        self.MO2mag_comboBox.setItemText(3, _translate("MainWindow", "16x"))
        self.MO2mag_comboBox.setItemText(4, _translate("MainWindow", "20x"))
        self.MO2mag_comboBox.setItemText(5, _translate("MainWindow", "25x"))
        self.MO2mag_comboBox.setItemText(6, _translate("MainWindow", "30x"))
        self.MO2mag_comboBox.setItemText(7, _translate("MainWindow", "40x"))
        self.MO2mag_comboBox.setItemText(8, _translate("MainWindow", "50x"))
        self.MO2mag_comboBox.setItemText(9, _translate("MainWindow", "60x"))
        self.MO2mag_comboBox.setItemText(10, _translate("MainWindow", "100x"))
        self.label_16.setText(_translate("MainWindow", "TL2 (mm)"))
        self.TL2_lineEdit.setPlaceholderText(_translate("MainWindow", "focal length"))
        self.label_13.setText(_translate("MainWindow", "SL2 (mm)"))
        self.SL2_lineEdit.setPlaceholderText(_translate("MainWindow", "focal length"))
        self.label_12.setText(_translate("MainWindow", "MO3"))
        self.MO3make_comboBox.setItemText(0, _translate("MainWindow", "Leica"))
        self.MO3make_comboBox.setItemText(1, _translate("MainWindow", "Mitutoyo"))
        self.MO3make_comboBox.setItemText(2, _translate("MainWindow", "Nikon"))
        self.MO3make_comboBox.setItemText(3, _translate("MainWindow", "Olympus"))
        self.MO3make_comboBox.setItemText(4, _translate("MainWindow", "Zeiss"))
        self.MO3mag_comboBox.setItemText(0, _translate("MainWindow", "4x"))
        self.MO3mag_comboBox.setItemText(1, _translate("MainWindow", "5x"))
        self.MO3mag_comboBox.setItemText(2, _translate("MainWindow", "10x"))
        self.MO3mag_comboBox.setItemText(3, _translate("MainWindow", "16x"))
        self.MO3mag_comboBox.setItemText(4, _translate("MainWindow", "20x"))
        self.MO3mag_comboBox.setItemText(5, _translate("MainWindow", "25x"))
        self.MO3mag_comboBox.setItemText(6, _translate("MainWindow", "30x"))
        self.MO3mag_comboBox.setItemText(7, _translate("MainWindow", "40x"))
        self.MO3mag_comboBox.setItemText(8, _translate("MainWindow", "50x"))
        self.MO3mag_comboBox.setItemText(9, _translate("MainWindow", "60x"))
        self.MO3mag_comboBox.setItemText(10, _translate("MainWindow", "100x"))
        self.label_18.setText(_translate("MainWindow", "TL3 (mm)"))
        self.TL3_lineEdit.setPlaceholderText(_translate("MainWindow", "focal length"))
        self.label_17.setText(_translate("MainWindow", "SL3 (mm)"))
        self.SL3_lineEdit.setPlaceholderText(_translate("MainWindow", "focal length"))
        self.label_15.setText(_translate("MainWindow", "SL1 (mm)"))
        self.label_14.setText(_translate("MainWindow", "TL1 (mm)"))
        self.label_11.setText(_translate("MainWindow", "MO1"))
        self.SL1_lineEdit.setPlaceholderText(_translate("MainWindow", "focal length"))
        self.G2_groupBox.setTitle(_translate("MainWindow", "G2 (DSLM galvo)"))
        self.label_4.setText(_translate("MainWindow", "V/° (mech)"))
        self.G1_groupBox.setTitle(_translate("MainWindow", "G1 (SOPi galvo)"))
        self.label.setText(_translate("MainWindow", "V/° (mech)"))
        self.camera_groupBox.setTitle(_translate("MainWindow", "Camera"))
        self.label_19.setText(_translate("MainWindow", "Width #"))
        self.pxsize_lineEdit.setPlaceholderText(_translate("MainWindow", "pixel size"))
        self.label_20.setText(_translate("MainWindow", "Height #"))
        self.label_21.setText(_translate("MainWindow", "Pixel (µm)"))
        self.heightpx_lineEdit.setPlaceholderText(_translate("MainWindow", "num. of pixels"))
        self.widthpx_lineEdit.setPlaceholderText(_translate("MainWindow", "num. of pixels"))
        self.label_22.setText(_translate("MainWindow", "*width is along longer dim"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cfg_tab), _translate("MainWindow", "CFG"))
        self.daq_groupBox.setTitle(_translate("MainWindow", "DAQ"))
        self.G1freq_label.setText(_translate("MainWindow", "VPS (Hz)"))
        self.scanrange1_lineEdit.setPlaceholderText(_translate("MainWindow", "µm "))
        self.offset2_label.setText(_translate("MainWindow", "Offset (µm)"))
        self.daq_trigenable_radioButton.setText(_translate("MainWindow", "Y/N"))
        self.connect_daq_pushButton.setText(_translate("MainWindow", "Connect"))
        self.G2_label.setText(_translate("MainWindow", "G2"))
        self.camtrig_label.setText(_translate("MainWindow", "Cam trig (Hz)"))
        self.scanrange_label.setText(_translate("MainWindow", "Scan range (µm)"))
        self.scanrange2_label.setText(_translate("MainWindow", "LS span (µm)"))
        self.offset2_lineEdit.setPlaceholderText(_translate("MainWindow", "µm"))
        self.VPS_comboBox.setItemText(0, _translate("MainWindow", "0.01"))
        self.VPS_comboBox.setItemText(1, _translate("MainWindow", "0.02"))
        self.VPS_comboBox.setItemText(2, _translate("MainWindow", "0.05"))
        self.VPS_comboBox.setItemText(3, _translate("MainWindow", "0.1"))
        self.VPS_comboBox.setItemText(4, _translate("MainWindow", "0.125"))
        self.VPS_comboBox.setItemText(5, _translate("MainWindow", "0.2"))
        self.VPS_comboBox.setItemText(6, _translate("MainWindow", "0.25"))
        self.VPS_comboBox.setItemText(7, _translate("MainWindow", "0.5"))
        self.VPS_comboBox.setItemText(8, _translate("MainWindow", "1"))
        self.VPS_comboBox.setItemText(9, _translate("MainWindow", "2"))
        self.VPS_comboBox.setItemText(10, _translate("MainWindow", "5"))
        self.VPS_comboBox.setItemText(11, _translate("MainWindow", "6"))
        self.VPS_comboBox.setItemText(12, _translate("MainWindow", "8"))
        self.VPS_comboBox.setItemText(13, _translate("MainWindow", "10"))
        self.VPS_comboBox.setItemText(14, _translate("MainWindow", "15"))
        self.VPS_comboBox.setItemText(15, _translate("MainWindow", "20"))
        self.VPS_comboBox.setItemText(16, _translate("MainWindow", "25"))
        self.TTLfreq_comboBox.setItemText(0, _translate("MainWindow", "01"))
        self.TTLfreq_comboBox.setItemText(1, _translate("MainWindow", "02"))
        self.TTLfreq_comboBox.setItemText(2, _translate("MainWindow", "04"))
        self.TTLfreq_comboBox.setItemText(3, _translate("MainWindow", "05"))
        self.TTLfreq_comboBox.setItemText(4, _translate("MainWindow", "08"))
        self.TTLfreq_comboBox.setItemText(5, _translate("MainWindow", "10"))
        self.TTLfreq_comboBox.setItemText(6, _translate("MainWindow", "16"))
        self.TTLfreq_comboBox.setItemText(7, _translate("MainWindow", "20"))
        self.TTLfreq_comboBox.setItemText(8, _translate("MainWindow", "40"))
        self.TTLfreq_comboBox.setItemText(9, _translate("MainWindow", "80"))
        self.offset_label.setText(_translate("MainWindow", "Offset (µm)"))
        self.offset1_lineEdit.setPlaceholderText(_translate("MainWindow", "µm"))
        self.scanrange2_lineEdit.setPlaceholderText(_translate("MainWindow", "µm"))
        self.laser_comboBox.setItemText(0, _translate("MainWindow", "Laser off"))
        self.laser_comboBox.setItemText(1, _translate("MainWindow", "Blue laser"))
        self.laser_comboBox.setItemText(2, _translate("MainWindow", "Green laser"))
        self.G1_label.setText(_translate("MainWindow", "G1"))
        self.stage_groupBox.setTitle(_translate("MainWindow", "Stage"))
        self.speed_label.setText(_translate("MainWindow", "Velocity (mm/s)"))
        self.recenter_pushButton.setText(_translate("MainWindow", "Re-center"))
        self.haltstage_Button.setText(_translate("MainWindow", "Halt"))
        self.label_3.setText(_translate("MainWindow", "Jog / Step"))
        self.velocity_comboBox.setItemText(0, _translate("MainWindow", "0.10"))
        self.velocity_comboBox.setItemText(1, _translate("MainWindow", "0.50"))
        self.velocity_comboBox.setItemText(2, _translate("MainWindow", "1.00"))
        self.velocity_comboBox.setItemText(3, _translate("MainWindow", "1.50"))
        self.velocity_comboBox.setItemText(4, _translate("MainWindow", "2.00"))
        self.velocity_comboBox.setItemText(5, _translate("MainWindow", "2.50"))
        self.velocity_comboBox.setItemText(6, _translate("MainWindow", "3.00"))
        self.velocity_comboBox.setItemText(7, _translate("MainWindow", "3.50"))
        self.velocity_comboBox.setItemText(8, _translate("MainWindow", "3.75"))
        self.velocity_comboBox.setItemText(9, _translate("MainWindow", "4.00"))
        self.connect_stage_pushButton.setText(_translate("MainWindow", "Connect"))
        self.label_7.setText(_translate("MainWindow", "Set limit"))
        self.Xneg_pushButton.setText(_translate("MainWindow", "X-"))
        self.Yneg_pushButton.setText(_translate("MainWindow", "Y-"))
        self.Ypos_pushButton.setText(_translate("MainWindow", "Y+"))
        self.Xpos_pushButton.setText(_translate("MainWindow", "X+"))
        self.Ypos_lim_pushButton.setText(_translate("MainWindow", "Y+"))
        self.Xpos_lim_pushButton.setText(_translate("MainWindow", "X+"))
        self.Xneg_lim_pushButton.setText(_translate("MainWindow", "X-"))
        self.Yneg_lim_pushButton.setText(_translate("MainWindow", "Y-"))
        self.location_display_label.setText(_translate("MainWindow", "(0.0,0.0) µm"))
        self.stepenable_radioButton.setText(_translate("MainWindow", "Step Y/N"))
        self.movestep_lineEdit.setPlaceholderText(_translate("MainWindow", "step µm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.control_tab), _translate("MainWindow", "Control"))

import crossbill_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

